#!/bin/sh /etc/rc.common
# Copyright (C) 2025 jiangtao-song

START=99
STOP=10

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/node /usr/lib/node_modules/node-red/red.js
	# 持久化数据目录
	procd_set_param env HOME=/root
	procd_set_param respawn
	procd_close_instance
}
